# Generated by Django 3.2.3 on 2023-05-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.TextField()),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'customer_data',
            },
        ),
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.TextField()),
                ('total_price', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_controller.customer')),
            ],
            options={
                'db_table': 'order_data',
            },
        ),
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.TextField()),
                ('prod_name', models.TextField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.TextField()),
            ],
            options={
                'db_table': 'product_data',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_controller.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_controller.orderdata')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_controller.productdata')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_stock', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_controller.productdata')),
            ],
            options={
                'db_table': 'inventory_data',
            },
        ),
    ]
